[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["Scripts*", "Assets*"]
namespaces = false

[project]
name = "roleenginea2"
version = "0.0.1"
description = "A Game Engine Made On Top Of Pygame"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "meson>=1.11.2",
    "numpy>=2.5.1",
    "pillow>=12.3.0",
    "pygame>=2.6.1",
    "pyinstaller>=6.21.0",
    "uvbox>=1.0.9",
]

[project.gui-scripts]
roleenginea2 = "RoleEngineA2:RoleEngineA2"
